package hello;

import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.core.Response;

import org.json.JSONObject;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import hello.Listing;
import hello.ListingRepository;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/listing") // This means URL's start with /demo (after Application path)
public class ListingRESTController {
//	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
//	private ListingRepository listingRepository;
	
	SQLAdapter sqlAdapter=new SQLAdapterImpl(); 
	
	@POST
	@RequestMapping("/create")
    public Response newListingData(@RequestParam(value="newListingData") JSONObject newListingData) {
        try {
			return Response.ok(sqlAdapter.persistNewListing(newListingData, 1)).build();
		} catch (WrongFormatException e) {
			return Response.notModified().status(406).build();
		}
    }
	
	@GET
	@RequestMapping("/get")
	public Response getListingById(@RequestParam(value="listingId") long listingId){
		try{
			return Response.ok(sqlAdapter.getListingById(listingId)).build();
		}catch(ListingNotFoundException e){
			return Response.notModified().status(404).build();
		}
	}
}
